import { CustomerStatusType } from "@/enums/customer-status-type";
import { LeadSourceType } from "@/enums/lead-source-type";
import IAccount from "./account";
import IUser from "./user";
import ICountry from "./country";
import IService from "./service";
import IPhoneNumber from "./phone-number";
import { SalutationType } from "@/enums";
import ICity from "./city";
import IPostalCode from "./postal-code";

export default interface ICustomer {
  id: number;
  first_name: string;
  last_name: string;
  title: string;
  email: string;
  priority: number;
  description: string;
  follow_up_date: Date | null;
  status: CustomerStatusType;
  salutation: SalutationType;
  lead_source: LeadSourceType;
  country_id: number;
  account_id: number;
  state_id: number;
  user_id: number;
  city_id: number;
  postal_code_id: number;
  customer_phone_number_id: number;
  account: IAccount;
  user: IUser;
  customer_phone_number: IPhoneNumber | null;
  country: ICountry;
  city: ICity;
  postal_code: IPostalCode;
  services: IService[];
  createdAt: Date;
  updatedAt: Date;
}
